### ISSUE TITLE
crash on startup with Qt 5.9.0 (mingw)

### ISSUE THREAD

**Issue by neolit123** [annulen/webkit#575]
i've installed this:
https://github.com/annulen/webkit/releases/download/qtwebkit-5.212.0-alpha2/qtwebkit-5.212.0_alpha2-qt59-mingw530-x86.zip

over my recent Qt 5.9.0 (MINGW) installation on Windows 7 from the official installer.

with this sample app:
```
#include <QApplication>
#include <QtWebKitWidgets>

int main(int argc, char ** argv)
{
	QApplication app(argc, argv);

	QWebView *view = new QWebView();
	view->load(QUrl("http://qt.nokia.com/"));
	view->show();

	return app.exec();
}
```

i get a:
`The application was unable to start correctly (0xc0000017)...`

all DLLs are found and in place.

any idea what might be causing that?

note1: happens for both debug and release builds.
note2: under a certain project where i want to integrate a QWebView i'm also getting a:
`QWidget: Must construct a QApplication before a QWidget`

**Comment by annulen** [comment]
>any idea what might be causing that?

Probably some DLL is missing. Did you check with Dependency Walker?

**Comment by neolit123** [comment]
yes, i did. no DLLs are missing according to Dependency Walker.
i've also checked with Process Monitor and there are no missing DLLs as far as it reaches, but then the error is shown exactly after this DLL is loaded:
`C:\bin\qt\5.9\mingw53_32\bin\Qt5Positioningd.dll`

have you tried integrating `qtwebkit-5.212.0_alpha2-qt59-mingw530-x86.zip`
into the official Qt 5.9.0 (MINGW 5.3.0)?

**Comment by annulen** [comment]
Is Qt5WebChannel(d).dll installed?

**Comment by neolit123** [comment]
yes, here is a pastebin of all the contents of the `C:\bin\qt\5.9\mingw53_32\bin` folder:
https://pastebin.com/xfksvbNX

**Comment by neolit123** [comment]
i was able to get the release build to work. re-installed the ZIP and restarted the OS - no idea why it works now. after including `ssleay32.dll, libssl32.dll, libeay32.dll` the release build even opens a web page.

for the debug build still the same error occurs:
`The application was unable to start correctly (0xc0000017)...`

here is an output of the compiler/ linker for "make debug":
https://pastebin.com/0TYdNQMr

what i notice is that in debug mode the linker is looking for the following libraries which don't exist on my end:
` -LC:/utils/my_sql/my_sql/lib -LC:/utils/postgresql/pgsql/lib`

here is Process Monitor output (CSV):
https://pastebin.com/PaRuHEgj

do you know how can i get the debug build to work?

**Comment by neolit123** [comment]
BTW, `C0000017` means `STATUS_NO_MEMORY` which can be thrown by HeapAlloc(). i wonder if the huge size of `Qt5WebKitd.dll` (1.25GB) is the cause for that...

**Comment by annulen** [comment]
But most of these 1.25GB is debug information that should not be loaded in normal execution

**Comment by neolit123** [comment]
that's true. so maybe "something" inside the DLL is trying to a allocate a lot of memory. have you tested Qt5WebKitd.dll on your side? i'm running Win7 64bit.

**Comment by raoulh** [comment]
Hi,
I have the exact same error with windows 10 64bits and Qt 5.9.1 mingw official release.
A simple app using qwebkit starts in release, but crashes with C0000017 in debug.

**Comment by aquiles2k** [comment]
I can confirm this error with qt5.9.1 32bit from msys2. Release works, debug crashes with C0000017.

**Comment by aquiles2k** [comment]
Anything i can do to help with this issue?

**Comment by annulen** [comment]
If you can build QtWebKit, you can help to figure out why debug binaries become so large. Currently I disable debug info for code that is not implementing public API, just like old build system was doing. See `USE_MINIMAL_DEBUG_INFO` in `Source/PlatformQt.cmake`. However, old build system (see `Tools/qmake/mkspecs/features/production_build.prf`) used release optimization flags for this code, while I'm using -O1 now. It might be that -O1 results in much larger code than -O3 which is used in release build, or some other compiler flags are used in debug build that inflate binary size so much.

**Comment by annulen** [comment]
Another approach, of course, is just to replace debug build with release + "d" suffixes

**Comment by annulen** [comment]
I've made a debug build locally.

> It might be that -O1 results in much larger code than -O3

Looks like this is not the case, e.g. libWebCored.a (intermediate library in debug build) is just 9.45 MB while corresponding libWebCore.a (release) is 5.86 MB. Something is screwed during linking of Qt5WebKitd.dll

**Comment by aquiles2k** [comment]
Sry but i just use the libs provided by msys2 because of not haveing to look into building it :) So i cant help with that. 

I currently circumvent the problem by debugging only in a 64bit build where the problem doesnt occur as i found out today (at least for me). This doesnt solve the underlying problem but at least i dont have to resort to debug using console output anymore :)

**Comment by annulen** [comment]
I've found a quick workaround: just run `strip bin\Qt5WebKitd.dll` in command line where MinGW tools are available

**Comment by annulen** [comment]
Please try binaries from http://download.qt.io/snapshots/ci/qtwebkit/qtwebkit/qtwebkit-Windows-Windows_7-Mingw53-Windows-Windows_7-X86.7z

**Comment by annulen** [comment]
Should be fixed now

**Comment by thomasrusche** [comment]
I have downloaded the mingw binaries from QtWebKit 5.212.0 Alpha 2 yesterday. The problem is not fixed for the Alpha 2 (yes, I read that the fix has been added to Alpha **3**). I get the same error: Release build is working. Debug build is crashing on startup.
I tried the following to make a Debug build work: Copied the release mode QtWebKit.dll and renamed to QtWebKitd.dll, and QtWebKitWidgetsd.dll respectively. This lead to another startup error "QWidget: Must construct a QApplication before a QWidget". Then I tried to run "strip bin\Qt5WebKitd.dll" on the original big debug file. This shrinked the file from 1.25 GB to as little as 86 MB. Now Debig is working, too! Thank You a lot for your helpful comments in this issue tracker!

**Comment by annulen** [comment]
You can try binaries from

http://download.qt.io/snapshots/ci/qtwebkit/5.9/1509048110/qtwebkit/qtwebkit-Windows-Windows_7-Mingw53-Windows-Windows_7-X86.7z

**Comment by dachangjin** [comment]
I've installed this:
[http://download.qt.io/snapshots/ci/qtwebkit/5.9/1509048110/qtwebkit/qtwebkit-Windows-Windows_7-Mingw53-Windows-Windows_7-X86.7z](url)

over my recent Qt 5.9.2 (MINGW) installation on Windows 7 from the official installer.
I was able to get the release build to work,also get the debug build to work.I got the **.exe file from release dir and run windeployqt **.exe. when i click the **.exe file,it could not launch the app because of error(0xc000007b).

**Comment by annulen** [comment]
Please make sure that all dll files from `bin` directory in QtWebKit archive are deployed with the application

**Comment by annulen** [comment]
Also try with http://download.qt.io/snapshots/ci/qtwebkit/5.9/latest/qtwebkit/

**Comment by dachangjin** [comment]
I have copied all the file from bin directory in QtWebKit archive to my application directory and it runs.Thank you!

**Comment by annulen** [comment]
Yep, sounds like fix in windeployqt is needed
